#APP-fluentD-MongoDB.
version: '3'
services:
  fluentd:
    build: ./fluentd
    links:
      - "mongo"
    ports:
      - "24224:24224"
      - "24224:24224/udp" 
  web:
    image: httpd
    ports:
      - "80:80"
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access    
    depends_on:
      - fluentd
 

  mongo:
    build: ./mongodb
    volumes:
      - ./mongodb:/data/db
    ports:
      - "27017:27017"
      - "8081:8081"
    environment:
      MONGODB_DATABASE: ${MONGODB_DATABASE}
    # command: mongod --smallfiles --logpath=/dev/null # --quiet
